### ISSUE TITLE
Error when running example in gvanno

### ISSUE THREAD

**Issue by nandan75** [sigven/gvanno#10]
Hi ,

I have installed gvanno using "Singularity" on my mac machine.

I am getting the following error..

My Command--->
python3 gvanno-1.4.1/gvanno.py --query_vcf gvanno-1.4.1/examples/example.grch38.vcf.gz --gvanno_dir gvanno-1.4.1 --output_dir run_example --sample_id example --genome_assembly grch38 --container singularity --force_overwrite

2021-04-15 15:43:00 - gvanno-start - INFO - --- Germline variant annotation (gvanno) workflow ----
2021-04-15 15:43:00 - gvanno-start - INFO - Sample name: example
2021-04-15 15:43:00 - gvanno-start - INFO - Genome assembly: grch38

2021-04-15 15:43:00 - gvanno-validate-input - INFO - STEP 0: Validate input data
Error for command "exec": unknown shorthand flag: 'W' in -W

Can someone assist?

thanks,

Nandan

**Comment by nandan75** [comment]
I am not sure what happens to the 

"docker pull sigven/gvanno:1.4.1 (gvanno annotation engine)"
Which is a .sif file?

Where is this used in the above command?

regards,

Nandan

**Comment by sigven** [comment]
Dear Nandan,

Thanks for reaching out.  I think this is a Singularity issue, I am trying to see what's causing it. Just to check: Have you built the singularity image, following the instructions here:

https://github.com/sigven/gvanno#11-installation-of-singularity-optional

The singularity part is contributed by another user, but according to the code, it seems you should have a a `gvanno.simg` in your `src`directory after installing Singularity for gvanno. Is that in place for you?

Tha above commend (`docker pull.. `) is used when running the Docker workflow, should not be run in `gvanno.py` when using the Singularity version I believe.

kind regards,
Sigve

**Comment by tinavisnovska** [comment]
Hi Nandan, 
which version of singularity are you running on your computer?

It looks like singularity exec command executed inside gvanno.py cannot make sense of the -W option, so I am wondering if that option is available in your installation at all.

best, 
tina

**Comment by nandan75** [comment]
Thanks Sigve and Tina for your responses.

I actually went ahead and used Docker to run gvanno and it ran seamlessly :-) on my local mac.

Thanks again,

Nandan
