### ISSUE TITLE
Uninitialized value $faidx

### ISSUE THREAD

**Issue by carbocation** [sigven/gvanno#3]
Inspecting my warnings, I'm seeing the following (thousands of times):
```
head onesample.gvanno_ready.vep.vcf_warnings.txt 
WARNING: 31 : Use of uninitialized value $faidx in split at /opt/vep/src/ensembl-vep/modules/LoF.pm line 499, <$fh> line 5031.
Use of uninitialized value $faidx in split at /opt/vep/src/ensembl-vep/modules/LoF.pm line 499, <$fh> line 5031.
Use of uninitialized value $faidx in split at /opt/vep/src/ensembl-vep/modules/LoF.pm line 499, <$fh> line 5031.
WARNING: 15 : Use of uninitialized value $faidx in split at /opt/vep/src/ensembl-vep/modules/LoF.pm line 499, <$fh> line 5031.
```

Is this OK to ignore? Or does it imply an issue with something I'm doing, or something in the script?

**Comment by sigven** [comment]
Hi, Yeah, I seem to remember this from my previous runs. It has to do with the loss-of-function prediction provided by LofTee. There was an [issue filed for this](https://github.com/konradjk/loftee/issues/18), but I believe it can be ignored. It's either way not something on your side.

**Comment by carbocation** [comment]
Going to close this since it is upstream.
