### ISSUE TITLE
Parameters to include dbNSFP?

### ISSUE THREAD

**Issue by carbocation** [sigven/gvanno#4]
From what I can tell from the README, the only configurables are whether or not to run LoFTee and some parameters affecting memory and CPU usage. In my output, I am not seeing some of the [dbNSFP 4.0 annotations, such as PrimateAI](https://drive.google.com/file/d/1omOORbJVYDfGsiVWGwSBj_LiX3oSPudU/view), nor does the header suggest that it should be there:

```
##VEP="v95" time="2019-03-26 16:54:00" cache="/usr/local/share/vep/data/homo_sapiens/95_GRCh38" ensembl=95.4f83453 ensembl-funcgen=95.94439f4 ensembl-io=95.78ccac5 ensembl-variation=95.858de3e 1000genomes="phase3" COSMIC="86" ClinVar="201810" ESP="V2-SSA137" HGMD-PUBLIC="20174" assembly="GRCh38.p12" dbSNP="151" gencode="GENCODE 29" genebuild="2014-07" gnomAD="170228" polyphen="2.2.2" regbuild="1.0" sift="sift5.2.2"
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|Consequence|IMPACT|SYMBOL|Gene|Feature_type|Feature|BIOTYPE|EXON|INTRON|HGVSc|HGVSp|cDNA_position|CDS_position|Protein_position|Amino_acids|Codons|Existing_variation|ALLELE_NUM|DISTANCE|STRAND|FLAGS|PICK|VARIANT_CLASS|SYMBOL_SOURCE|HGNC_ID|CANONICAL|APPRIS|CCDS|ENSP|SWISSPROT|TREMBL|UNIPARC|RefSeq|DOMAINS|HGVS_OFFSET|AF|AFR_AF|AMR_AF|EAS_AF|EUR_AF|SAS_AF|gnomAD_AF|gnomAD_AFR_AF|gnomAD_AMR_AF|gnomAD_ASJ_AF|gnomAD_EAS_AF|gnomAD_FIN_AF|gnomAD_NFE_AF|gnomAD_OTH_AF|gnomAD_SAS_AF|CLIN_SIG|SOMATIC|PHENO|LoF|LoF_filter|LoF_flags|LoF_info">
##LoF=Loss-of-function annotation (HC = High Confidence; LC = Low Confidence)
##LoF_filter=Reason for LoF not being HC
##LoF_flags=Possible warning flags for LoF
##LoF_info=Info used for LoF annotation
```

Are there command-line or .toml parameters that we can use to configure this to extract the desired fields from dbNSFP?

**Comment by sigven** [comment]
Hi,

Since I distribute gvanno with a databundle, and since I do not want to deal with license-restricted datasets, the parts of dbNSFP that comes with gvanno are only those that are not restricted through licensing. This excludes some of the predictions in dbNSFP, PolyPhen2 most importantly. If I have missed PrimateAI and this is not limited by licensing, I will for sure fix this and include it.

best,
Sigve

**Comment by carbocation** [comment]
Ahh, this is good to know. Correct me if wrong, but if I simply agree with the `dbNSFP` license and download it, that won't be sufficient to include the missing annotations because I'd need to modify the underlying code? Thanks for all of your help by the way.

**Comment by sigven** [comment]
Yeah, afraid so. I essentially make a dbNSFP VCF file that contains the main prediction info per algo from the dbNSFP dataset (i.e. 'damaging' versus 'tolerated' according to the thresholds given in the dbNSFP README). If you have some patience, I can try to make a specific bundle that fits your needs, including all the license-restricted algorithms (which of course should be fine in an academic setting).

**Comment by carbocation** [comment]
Oh, that is OK - I can use the VEP Docker instance which should work out OK for my needs - just will require a bit more config than your combined tool! Again, I appreciate all your help.
