### ISSUE TITLE
run without installing python 3.6

### ISSUE THREAD

**Issue by travelanywhere** [sigven/gvanno#6]
Hello,

Is there an easy way to run gvanno without installing python 3.6? Is it for example possible with an docker container that has python 3.6?

**Comment by sigven** [comment]
Hi,

Python 3.6 is a requirement for gvanno. I would not recommend installing it inside a Docker container (i.e. "Docker inside Docker"), and I am really not sure if the Singularity mode would work here. 

regards,
Sigve
