### ISSUE TITLE
docker error response

### ISSUE THREAD

**Issue by paniscusJr** [sigven/gvanno#9]
Hi,

I am attempting to run gvanno 1.4.1. When I run the test data with the example command I am getting an error from Docker. Do you have any idea what might be causing this? 

python ./gvanno-1.4.1/gvanno_print.py --query_vcf /scratch/gvanno/gvanno-1.4.1/examples/example.grch38.vcf.gz \
--gvanno_dir /scratch/gvanno/gvanno-1.4.1 --output_dir /scratch/ \
--sample_id example --genome_assembly grch38 --container docker --force_overwrite

docker: Error response from daemon: error while creating mount source path '/scratch': mkdir : permission denied.

**Comment by sigven** [comment]
Hi,

Although I am not completely sure, I think this problem is due to file/folder permissions on your local computer (/scratch). I would have tried to test with different output directories to see if that helped. Not completely sure what `gvanno_print.py`refers to though.
